### ISSUE TITLE
Trouble with CAS locally

### ISSUE THREAD

**Issue by IuriGarcia** [bioatlas/ala-docker#35]
Hello!

I'm trying to add CAS to my cluster and im testing it locally. this is how my docker-compose looks like:

```
version: '3.7'

services:
  cas:
    image: cas
    ports:
      - 8080:8080
      - 8089:8443
    volumes:
      - ./config/cas.properties:/tmp/cas.properties
    command: /bin/ash -c  "sleep 80 && envsubst < /tmp/cas.properties > /data/cas/config/cas.properties && catalina.sh run"
    links:
      - mysqldbcas
    depends_on:
 
      - mysqldbcas

  mysqldbcas:
    image: mysql:5.7
    env_file: ./env/envcas.template
    container_name: mysqldbcas
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data_mysqldbcas:/var/lib/mysql

  userdetails:
    image: userdetails
    container_name: userdetails
    domainname: localhost
    env_file: ./env/.envcas
    volumes:
      - ./config/userdetails-config.properties:/tmp/userdetails-config.properties 
    command: /bin/ash -c "sleep 80 && envsubst < /tmp/userdetails-config.properties > /data/userdetails/config/userdetails-config.properties && catalina.sh run"
    depends_on:
 
      - mysqldbcas

volumes:
  cas_data:
  mongodb_data:
    driver: local
  db_data_mysqldbcas:
```

i've created the images with the Dockerfiles. I dont know how to correctly setup the conf files. My CAS container keeps showing that

`cas_1          | 2019-04-17 21:53:03,369 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 1 services.>
cas_1          | 2019-04-17 21:55:02,991 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
cas_1          | 2019-04-17 21:55:02,992 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|imaps?)://.*>
cas_1          | 2019-04-17 21:55:02,992 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 1 services.>
cas_1          | 2019-04-17 21:57:02,991 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
cas_1          | 2019-04-17 21:57:02,991 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|imaps?)://.*>
cas_1          | 2019-04-17 21:57:02,992 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 1 services.>`

And i cant accesse cas throw localhost:8089/cas/login
